<?php

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property string $url
 * @property clob $description
 * @property Product $Product
 * 
 * @method integer getProductId()   Returns the current record's "product_id" value
 * @method string  getUrl()         Returns the current record's "url" value
 * @method clob    getDescription() Returns the current record's "description" value
 * @method Product getProduct()     Returns the current record's "Product" value
 * @method Image   setProductId()   Sets the current record's "product_id" value
 * @method Image   setUrl()         Sets the current record's "url" value
 * @method Image   setDescription() Sets the current record's "description" value
 * @method Image   setProduct()     Sets the current record's "Product" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}