<?php

/**
 * BaseUserProductUploadLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $product_id
 * @property User $User
 * @property Product $Product
 * 
 * @method integer               getUserId()     Returns the current record's "user_id" value
 * @method integer               getProductId()  Returns the current record's "product_id" value
 * @method User                  getUser()       Returns the current record's "User" value
 * @method Product               getProduct()    Returns the current record's "Product" value
 * @method UserProductUploadLink setUserId()     Sets the current record's "user_id" value
 * @method UserProductUploadLink setProductId()  Sets the current record's "product_id" value
 * @method UserProductUploadLink setUser()       Sets the current record's "User" value
 * @method UserProductUploadLink setProduct()    Sets the current record's "Product" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserProductUploadLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_product_upload_link');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}