<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $product_id
 * @property integer $rating
 * @property integer $love
 * @property clob $content
 * @property User $User
 * @property Product $Product
 * 
 * @method integer getUserId()     Returns the current record's "user_id" value
 * @method integer getProductId()  Returns the current record's "product_id" value
 * @method integer getRating()     Returns the current record's "rating" value
 * @method integer getLove()       Returns the current record's "love" value
 * @method clob    getContent()    Returns the current record's "content" value
 * @method User    getUser()       Returns the current record's "User" value
 * @method Product getProduct()    Returns the current record's "Product" value
 * @method Comment setUserId()     Sets the current record's "user_id" value
 * @method Comment setProductId()  Sets the current record's "product_id" value
 * @method Comment setRating()     Sets the current record's "rating" value
 * @method Comment setLove()       Sets the current record's "love" value
 * @method Comment setContent()    Sets the current record's "content" value
 * @method Comment setUser()       Sets the current record's "User" value
 * @method Comment setProduct()    Sets the current record's "Product" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('love', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}