<?php

/**
 * BaseProductSimilarity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id1
 * @property integer $id2
 * @property float $similarity
 * @property Product $Product1
 * @property Product $Product2
 * 
 * @method integer           getId1()        Returns the current record's "id1" value
 * @method integer           getId2()        Returns the current record's "id2" value
 * @method float             getSimilarity() Returns the current record's "similarity" value
 * @method Product           getProduct1()   Returns the current record's "Product1" value
 * @method Product           getProduct2()   Returns the current record's "Product2" value
 * @method ProductSimilarity setId1()        Sets the current record's "id1" value
 * @method ProductSimilarity setId2()        Sets the current record's "id2" value
 * @method ProductSimilarity setSimilarity() Sets the current record's "similarity" value
 * @method ProductSimilarity setProduct1()   Sets the current record's "Product1" value
 * @method ProductSimilarity setProduct2()   Sets the current record's "Product2" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductSimilarity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_similarity');
        $this->hasColumn('id1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('similarity', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product as Product1', array(
             'local' => 'id1',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product as Product2', array(
             'local' => 'id2',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}