<?php

/**
 * BaseFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id1
 * @property integer $id2
 * @property integer $hop
 * @property User $User1
 * @property User $User2
 * 
 * @method integer    getId1()   Returns the current record's "id1" value
 * @method integer    getId2()   Returns the current record's "id2" value
 * @method integer    getHop()   Returns the current record's "hop" value
 * @method User       getUser1() Returns the current record's "User1" value
 * @method User       getUser2() Returns the current record's "User2" value
 * @method Friendship setId1()   Sets the current record's "id1" value
 * @method Friendship setId2()   Sets the current record's "id2" value
 * @method Friendship setHop()   Sets the current record's "hop" value
 * @method Friendship setUser1() Sets the current record's "User1" value
 * @method Friendship setUser2() Sets the current record's "User2" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendship');
        $this->hasColumn('id1', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id2', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('hop', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as User1', array(
             'local' => 'id1',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User as User2', array(
             'local' => 'id2',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}