<?php

/**
 * BaseColor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $colorname
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $ProductColorLink
 * 
 * @method string              getColorname()        Returns the current record's "colorname" value
 * @method Doctrine_Collection getProduct()          Returns the current record's "Product" collection
 * @method Doctrine_Collection getProductColorLink() Returns the current record's "ProductColorLink" collection
 * @method Color               setColorname()        Sets the current record's "colorname" value
 * @method Color               setProduct()          Sets the current record's "Product" collection
 * @method Color               setProductColorLink() Sets the current record's "ProductColorLink" collection
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('color');
        $this->hasColumn('colorname', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product', array(
             'refClass' => 'ProductColorLink',
             'local' => 'color_id',
             'foreign' => 'product_id'));

        $this->hasMany('ProductColorLink', array(
             'local' => 'id',
             'foreign' => 'color_id'));
    }
}