<?php

/**
 * BaseQQUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $user_id
 * @property User $User
 * 
 * @method string  getName()    Returns the current record's "name" value
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method User    getUser()    Returns the current record's "User" value
 * @method QQUser  setName()    Sets the current record's "name" value
 * @method QQUser  setUserId()  Sets the current record's "user_id" value
 * @method QQUser  setUser()    Sets the current record's "User" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQQUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('q_q_user');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}