<?php

/**
 * BaseProductColorLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $color_id
 * @property Product $Product
 * @property Color $Color
 * 
 * @method integer          getProductId()  Returns the current record's "product_id" value
 * @method integer          getColorId()    Returns the current record's "color_id" value
 * @method Product          getProduct()    Returns the current record's "Product" value
 * @method Color            getColor()      Returns the current record's "Color" value
 * @method ProductColorLink setProductId()  Sets the current record's "product_id" value
 * @method ProductColorLink setColorId()    Sets the current record's "color_id" value
 * @method ProductColorLink setProduct()    Sets the current record's "Product" value
 * @method ProductColorLink setColor()      Sets the current record's "Color" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductColorLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_color_link');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('color_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Color', array(
             'local' => 'color_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}