<?php

/**
 * BaseBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $country
 * @property clob $description
 * @property Doctrine_Collection $Products
 * 
 * @method string              getCountry()     Returns the current record's "country" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getProducts()    Returns the current record's "Products" collection
 * @method Brand               setCountry()     Sets the current record's "country" value
 * @method Brand               setDescription() Sets the current record's "description" value
 * @method Brand               setProducts()    Sets the current record's "Products" collection
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBrand extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('brand');
        $this->hasColumn('country', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product as Products', array(
             'local' => 'id',
             'foreign' => 'brand_id'));
    }
}