<?php

/**
 * BaseCategoryTree
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $subcategory_id
 * @property Category $Category
 * @property Category $Subcategory
 * 
 * @method integer      getCategoryId()     Returns the current record's "category_id" value
 * @method integer      getSubcategoryId()  Returns the current record's "subcategory_id" value
 * @method Category     getCategory()       Returns the current record's "Category" value
 * @method Category     getSubcategory()    Returns the current record's "Subcategory" value
 * @method CategoryTree setCategoryId()     Sets the current record's "category_id" value
 * @method CategoryTree setSubcategoryId()  Sets the current record's "subcategory_id" value
 * @method CategoryTree setCategory()       Sets the current record's "Category" value
 * @method CategoryTree setSubcategory()    Sets the current record's "Subcategory" value
 * 
 * @package    wepost
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryTree extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_tree');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('subcategory_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category as Subcategory', array(
             'local' => 'subcategory_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}