<?php

/**
 * CategoryTreeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTreeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTreeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryTree');
    }
}