<?php

/**
 * PriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Price');
    }
}