<?php

/**
 * ProductMaterialLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductMaterialLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductMaterialLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductMaterialLink');
    }
}