<?php

/**
 * ProductSimilarityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSimilarityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSimilarityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSimilarity');
    }
}