<?php

/**
 * QQUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QQUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QQUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QQUser');
    }
}