<?php

/**
 * RenRenUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RenRenUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RenRenUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RenRenUser');
    }
}