<?php

/**
 * SaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sale');
    }
}