<?php

/**
 * UserProductUploadLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProductUploadLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProductUploadLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProductUploadLink');
    }
}