<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/06 13:01:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=wepost',
  'username' => 'root',
  'password' => 'myhome515',
  'name' => 'doctrine',
)),);
